time:
  dt_minutes: 5
  horizon_hours: 48

network:
  n_stations: 3
  capacity_default: 12
  travel_time_min: [[0, 7, 10], [7, 0, 6], [10, 6, 0]]
  distance_km: [[0, 2.1, 3.2], [2.1, 0, 1.8], [3.2, 1.8, 0]]

demand:
  base_lambda_per_dt: 0.8 # arrivals per station per 5-min (antes dos fatores)

ops:
  strategy: greedy
  thresholds: { low: 0.2, high: 0.8 }

energy:
  chargers_per_station: [2, 2, 2]
  charge_rate_soc_per_hour: [0.25, 0.25, 0.25] # +25% SoC per hour when plugged
  battery_kwh_per_vehicle: 0.5
  energy_cost_per_kwh_eur: 0.20
